/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Modelo.Contructor;
import javax.swing.JOptionPane;

/**
 *
 * @author APRENDIZ
 */
public class Ingreso_Usuarios extends javax.swing.JFrame {

     public Contructor usuario;

    public Ingreso_Usuarios(Contructor ct) {
    this.usuario = ct;
    initComponents();
    
    
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNumCuenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfContrasena = new javax.swing.JTextField();
        btIngresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btCrearUsuario = new javax.swing.JButton();
        rdAhorro = new javax.swing.JRadioButton();
        rdCorriente = new javax.swing.JRadioButton();
        rdAdmin = new javax.swing.JRadioButton();

        buttonGroup1.add(rdAdmin);
        buttonGroup1.add(rdAhorro);
        buttonGroup1.add(rdCorriente);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Bienvenido");

        jLabel2.setText("Numero de Cuenta");

        jLabel3.setText("Contraseña");

        btIngresar.setText("Ingresar");
        btIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarActionPerformed(evt);
            }
        });

        jLabel4.setText("¿Sin usuario?");

        btCrearUsuario.setText("Crear Usuario");
        btCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearUsuarioActionPerformed(evt);
            }
        });

        rdAhorro.setText("Cuenta Ahorro");

        rdCorriente.setText("Cuenta Corriente");

        rdAdmin.setText("Admin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tfNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tfContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(rdAhorro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdCorriente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdAdmin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(btIngresar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btCrearUsuario)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdAhorro)
                    .addComponent(rdCorriente)
                    .addComponent(rdAdmin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btCrearUsuario))
                .addGap(28, 28, 28)
                .addComponent(btIngresar)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarActionPerformed
  
   int tipoCuenta = 0;
    
    // Determinar el tipo de cuenta según la selección
    if(rdAdmin.isSelected()){
        tipoCuenta = 3;
    } else if(rdAhorro.isSelected()){
        tipoCuenta = 1;
    } else if(rdCorriente.isSelected()){
        tipoCuenta = 2;
    }

    int numCuentaIngresada = Integer.parseInt(tfNumCuenta.getText());
    String contrasenaIngresada = tfContrasena.getText();
    
    // Validar el usuario a partir de la lista estática de usuarios
    Contructor usuarioValidado = Contructor.validarUsuario(numCuentaIngresada, contrasenaIngresada, tipoCuenta);
    
    if (usuarioValidado != null) {        
        // Si el usuario es validado, redirigir a la interfaz correspondiente
        if(tipoCuenta == 3){
            Interfaz_Principal ip = new Interfaz_Principal();
            ip.setVisible(true);
        } else {
            Interfaz_Principal_Usuario ipu = new Interfaz_Principal_Usuario(usuarioValidado);
            ipu.setVisible(true);
        }
        
        this.dispose(); // Cerrar el formulario de inicio de sesión
    } else {
        // Si el usuario no es encontrado, mostrar un mensaje de error
        JOptionPane.showMessageDialog(null, "Número de cuenta o contraseña incorrectos.");
    }
    }//GEN-LAST:event_btIngresarActionPerformed

    private void btCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearUsuarioActionPerformed

        Crear_Usuario cu = new Crear_Usuario();
        cu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCrearUsuarioActionPerformed


    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCrearUsuario;
    private javax.swing.JButton btIngresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rdAdmin;
    private javax.swing.JRadioButton rdAhorro;
    private javax.swing.JRadioButton rdCorriente;
    private javax.swing.JTextField tfContrasena;
    private javax.swing.JTextField tfNumCuenta;
    // End of variables declaration//GEN-END:variables
}
